name: 'Formal Spec Generator'
description:
  'Generates formal specifications for a project using the GPT API and Halmos.'
author: 'The Digital Defense Company'

inputs:
  summary:
    description: 'Summary of the repository'
    required: true
  demo_mode:
    description: 'Run in demo mode with hardcoded values'
    required: false
    default: 'false'

outputs:
  file_path:
    description: 'Path of the created or modified file'

runs:
  using: docker
  image: Dockerfile
